#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 10 23:18:21 2018

@author: dmilakov

Combines outfiles of several processes/settings

"""
import argparse, sys
import harps.io as io

def main(args):
    inputs = args.input
    output = args.output
    
    data_in = [io.read_textfile(file) for file in inputs]
    header =  io.to_string(['# {file}'.format(file=file) for file in inputs])
    
    io.write_textfile(data_in,output,header)
    
    return
if __name__=='__main__':
    parser = argparse.ArgumentParser(description='Combine "outlist" files ')
    parser.add_argument('input',nargs='?',
                        help='Paths to the input outlist files')
    parser.add_argument('--output',nargs='?',default=sys.stdout,
                        help='Path to the output file')
    args = parser.parse_args()
    print(args)
    main(args)